### ISSUE TITLE
Warning when using additional parameters

### ISSUE THREAD

**Issue by metaodi** [swinton/screenshot-website#2]
I'm using this action to create fullscreen screenshots of a website, that loads after some seconds. Therefore I use the `delay` and  `full-screen` parameter. Since today ([example run](https://github.com/openZH/covid_19/actions/runs/108426182)) there is a warning displayed (as annotation):

```
Unexpected input 'delay', valid inputs are ['source', 'destination']
```

I don't know if something changed at GitHub to now detect non-specified arguments.

Is there a way to get rid of the warning?

**Comment by swinton** [comment]
Hi! That's unfortunate about [the warning](https://github.com/openZH/covid_19/actions/runs/108426182) 🤔 

> Is there a way to get rid of the warning?

I would happily accept a PR to add the params you need as official inputs to the action, i.e. [here](https://github.com/swinton/screenshot-website/blob/ebee86398fa0b725f4080fd8a016d845211dd279/action.yml#L3-L10):

https://github.com/swinton/screenshot-website/blob/ebee86398fa0b725f4080fd8a016d845211dd279/action.yml#L3-L10

**Comment by metaodi** [comment]
@swinton thanks, I created PR #3 to add at least _my_ params to avoid these warnings. Maybe there will be a flag in the future to allow arbitrary inputs.

Others have similar issues: https://github.com/octokit/request-action/issues/26

**Comment by swinton** [comment]
Thanks for the PR! This is now available on [the `v1.x` release branch](https://github.com/swinton/screenshot-website/blob/v1.x/action.yml).

Using that branch should resolve this issue.

**Comment by metaodi** [comment]
It works, thanks!
