### ISSUE TITLE
save file in repository

### ISSUE THREAD

**Issue by amcaw** [swinton/screenshot-website#24]
I can't find the way to save the screenshot as artifact AND in the repository. Is it possible ? Maybe it's a dumb question but my Action fails everytime I try to update my repo with a screenshot. Thanks !

**Comment by swinton** [comment]
Are you trying to commit the artifact to the repo? Maybe [`swinton/commit`](https://github.com/swinton/commit) can help?

**Comment by amcaw** [comment]
Thanks, I'll try !
