### ISSUE TITLE
Proposal for collaborative maintenance of this project

### ISSUE THREAD

**Issue by jcfr** [swinton/screenshot-website#37]
@swinton  Thanks for putting together this streamlined GitHub Action :pray: :100: 

Would you consider adding other maintainers to help integrate outstanding pull requests and performing general maintenance ?

In the meantime, you will find the following pull requests:
* https://github.com/swinton/screenshot-website/pull/35
* https://github.com/swinton/screenshot-website/pull/36

**Comment by spier** [comment]
I see a couple of warnings in my GitHub Actions workflow that I think stem from the `swinton/screenshot-website@v1.x` GHA:

> The following actions uses node12 which is deprecated and will be forced to run on node16: swinton/screenshot-website@v1.x. For more info: https://github.blog/changelog/2023-06-13-github-actions-all-actions-will-run-on-node16-instead-of-node12-by-default/Show

> The `set-output` command is deprecated and will be disabled soon. Please upgrade to using Environment Files. For more information see: https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/

@jcfr I saw that you started this thread some months back. Did you have any luck reaching @swinton?

Would be great if we could collaborate here to get this GHA back into a state where we can all continue to uses it. And yes, that means that I am offering my help as well :)

**Comment by jcfr** [comment]
> Did you have any luck reaching @swinton?

I haven't received a response so far.

> And yes, that means that I am offering my help as well :)

That is great. Thanks for offering to help.


> back into a state where we can all continue to uses it.

I completely agree. It's essential to find a solution that ensures ongoing collaboration and maintenance.

I am thinking of a few options:

### (1) https://github.com/jcfr

We could consider using my personal fork of the project as its new home.

### (2) https://github.com/Slicer

Since we are currently using this action in the context of continuous integration for the `slicer.org` website[^1][^2], we might want to create a fork within the Slicer organization.

I'll make sure to discuss this with the community before making any decisions, but I don't anticipate any issues.

### Other GitHub user or organization ?

If you have any other suggestions for a more suitable home, please feel free to share.


[^1]: https://github.com/Slicer/slicer.org/tree/main/.github/actions/screenshot-website-imgur-upload
[^2]: https://github.com/Slicer/slicer.org/blob/main/.github/workflows/build-website.yml

**Comment by spier** [comment]
I don't have a strict preference.

Of course it would be best if we could keep it where it is (i.e. at https://github.com/swinton/screenshot-website) as that might allow us to make the fixes without breaking existing workflows of other users.

However I agree that currently it looks like that might not be possible.

In that case, we could start at https://github.com/jcfr and make all fixes that we need to make. Once we got things working, we can still to move the project into the https://github.com/Slicer org, if you want. 

We probably don't have to think about the "where should it live" decision that much right now, as I assume that your fork at https://github.com/jcfr/screenshot-website doesn't have that many users right now, does it? :) i.e. we could move it later without much disruption?

**Comment by swinton** [comment]
> Would you consider adding other maintainers to help integrate outstanding pull requests and performing general maintenance ?

Yes, definitely. Thank you for the proposal and apologies for my delay in responding.

@jcfr I've invited you to the repo, so you should have push access.

![image](https://github.com/swinton/screenshot-website/assets/27806/0fd64d70-2550-4426-bb7b-5cd36c785b8e)

Happy to also discuss a more suitable long-term plan, perhaps under a dedicated org. Feel free to email me directly as well, stevewinton[at]gmail 🙏

**Comment by jcfr** [comment]
To follow-up on this, @swinton invited me to collaborate :pray: , waiting we settle on a more longer term plan, this should allow to move forward :rocket:

**Comment by spier** [comment]
Very awesome to hear!

**Comment by jcfr** [comment]
### Update

> The `set-output` command is deprecated and will be disabled soon.

For future reference, this has been addressed in the following pull request:
* https://github.com/swinton/screenshot-website/pull/64

### Next

Release of `v1.1.0` along with update of branch `v1.x` will happen soon.

**Comment by spier** [comment]
@jcfr that's great.

I tested this in my workflow directly from `/screenshot-website@main`.
Can confirm that this made the `set-output` warning disappear :)

**Comment by jcfr** [comment]
> Can confirm that this made the `set-output` warning disappear :)

Thanks for confirming it works on your side :100:

**Comment by spier** [comment]
@jcfr are you still planning to cut the `v1.1.0` release, or did you run out of time? :) I totally understand in any case, this happens!
